language: node_js
node_js:
  - "12"
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: a2hUDwM96oje3BUtbBLZSYapb0MxBWwq+FX+C08M4POcENIgFPZonhKan0yIBXKkq3qn7m7ab++th+XitBU6DICjnLX19BcWpLTohQE1IKJ/qbTcF8SwTGI73RBdyWKkCxIF3hGG+WSnpZO5nd8KzkLv6h1dFTG9WhBl2tABvMgXiK/wk6hYnPE5bk+8Nwqz5G+EibCmdJqHh1Tu9rHdfVvPeP3D4pb0nvfhnSjRX06Q+IJZ2X5puhfdxEAddY8+faL4hE95Xtuj+s35AqaYyZyzbDmrpBFyCtQkQBZ6rZVlpTpNlSBtxx5V1I1g7l27brrkKO1AxcyPFuBsURupIR7pKo3AYPKkRfewGB2XBPWRFYnvuTLD4EjPHtz8ZTsHX1gIqxfOkODUCp6uIN6tlm2kF+oGvz4S8sVerBRU1D6du2xS1tUX7ZZSfA+08EGDgw+TPZoWwex1uVkX8ViFVpL93VQ7AGYxoLkVs+ZXv79+VwtaRO6UoXQM4XuWgpQs3idZlsTegioxVopCNDxI6Z2Hix89G2089vQY3Aphz1SlhTvrlwUTadJFl6ohm5aFgXCPDycQdWyb0MCYJIuhgEdTT6Fi+dvVmdeVKAj/nHyb7fXJsygiiBXDmean5CZ4MjGVwPunSuXceOorSdoJn45pvXZfowIxNdmtgz03Fmo=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
  - provider: npm
    edge: true
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: giukn8KBo+sI6aMe6/b7vyaJf2l/orNmiyLSFyoaNz5AL8Jg+2r8kl5GE+m+raQAK/D3JLUBX9P4mpiiMc8ejaUHyj5Z6tBOuhNJmxyz1qY46pKVxOq6C3VIWsEfaV2o6cOjzq1iv4XWDNUP0tB2JXUxICFuTeSh+JT0kiDQHm9/9kfz1id9NNGUU0sTFzHXRrHDdirrFK2onZokpKW3fc5TdSsm/Urup0CE7Jg17rgNbpfsPq/DnMffpLmMxcWCFXXLtL5y6SuiAq6huhhd51/6xMJGzt4dcFmhXij+bvDAQ2b67yzFRHl/Perc6UkpZnhQ+BPuwB0pAXsF/ctnbppngltaa/9ojBMQDZNlERrhZpAABVG6lrkQuhQXWSxlIWbyrrTQmobbFVnwPrPIFiIYi21X1s4XbzFRSq1f6YfkI8t2mp2vMn6PXflvfrYOPQRkVbWcKo9kdQJPGH/LQFPZrjIMNDSIbRgqupP6j25IA9ZacEm8JF6RrX5OW7It4IpgoHeAAP/uci5RxTb89xD+/L8nxfeeu/zbwKzjWFqi5p4YDadV9zqDSS9mke+OL8Dq4x9iwWf8wXmXUcjTN/ROjvPTG78NadZyWnNbiStuEIRiIpLWvv6rW5DlxgGEQi9EanAibu0qRwRRiT7kw8d3nsQncxTLoe9fE6gpVro=
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
