language: node_js
node_js:
  - "12"
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: BwpRRRjMv/Qqvu9lqvGjqZbec+1GHXrHr39/ANTLIHn1WR/B6XK7MxGMPIuSG7H5HvJ2g67eNFKxOI/HD6WEC0k6cAXGEz8rxCRfrRlW+EmaccXVfHTvCWWHoIoVs6e24FLXXU2qVOg8zDFZO+Ld9ZnJQwt8IZ/Wfwj+YRF+obsPHr24+oWgRezJMaoMayIG2IGtmynyE9OBJeysBFXrFtq0kFIq+tJFZC7NHooJbI/Q9Z15Z4r9hr8fS5pnP9JA+oH2CJv8jaFLM1oJPhGLhwWihwink2ra3ZwDsLuMu8s8/wEAFifur2iyGZIcNMcGWIgVlT9N3n8r4Rfvj3Emxobj7v62WYQugxT61d2JX35fvbIRxM1ZIumhWKGBlYbyZXloJQIbqROAyqBcG3eTmOK0I/2QPVGVYJwUaK7Ef5ggU7IMCpOGLzbMfnxkIhZlCrTknGwBp4kZhBQRAkO/kCBBolQ88kNoIGAY1FkNWIdq68BYczlImf+Bam0UiIUIeSSv2FUJ78ZckjHpuyhsQvw7LQqv9JuDtY3V+WGdZsM1YZ0Za7MWz0fABpAKbs0ijB5cN2TW9jDqKwF3QlvaZUzORCeEgCvAR5cNmwQipKVdoLHLxcM8xuumdKhtKai/HvB9gOXHNFm3lQagyhIcxTIvf0usB0j9ui8Kf99WclA=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
  - provider: npm
    edge: true
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: giukn8KBo+sI6aMe6/b7vyaJf2l/orNmiyLSFyoaNz5AL8Jg+2r8kl5GE+m+raQAK/D3JLUBX9P4mpiiMc8ejaUHyj5Z6tBOuhNJmxyz1qY46pKVxOq6C3VIWsEfaV2o6cOjzq1iv4XWDNUP0tB2JXUxICFuTeSh+JT0kiDQHm9/9kfz1id9NNGUU0sTFzHXRrHDdirrFK2onZokpKW3fc5TdSsm/Urup0CE7Jg17rgNbpfsPq/DnMffpLmMxcWCFXXLtL5y6SuiAq6huhhd51/6xMJGzt4dcFmhXij+bvDAQ2b67yzFRHl/Perc6UkpZnhQ+BPuwB0pAXsF/ctnbppngltaa/9ojBMQDZNlERrhZpAABVG6lrkQuhQXWSxlIWbyrrTQmobbFVnwPrPIFiIYi21X1s4XbzFRSq1f6YfkI8t2mp2vMn6PXflvfrYOPQRkVbWcKo9kdQJPGH/LQFPZrjIMNDSIbRgqupP6j25IA9ZacEm8JF6RrX5OW7It4IpgoHeAAP/uci5RxTb89xD+/L8nxfeeu/zbwKzjWFqi5p4YDadV9zqDSS9mke+OL8Dq4x9iwWf8wXmXUcjTN/ROjvPTG78NadZyWnNbiStuEIRiIpLWvv6rW5DlxgGEQi9EanAibu0qRwRRiT7kw8d3nsQncxTLoe9fE6gpVro=
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
