language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: a2hUDwM96oje3BUtbBLZSYapb0MxBWwq+FX+C08M4POcENIgFPZonhKan0yIBXKkq3qn7m7ab++th+XitBU6DICjnLX19BcWpLTohQE1IKJ/qbTcF8SwTGI73RBdyWKkCxIF3hGG+WSnpZO5nd8KzkLv6h1dFTG9WhBl2tABvMgXiK/wk6hYnPE5bk+8Nwqz5G+EibCmdJqHh1Tu9rHdfVvPeP3D4pb0nvfhnSjRX06Q+IJZ2X5puhfdxEAddY8+faL4hE95Xtuj+s35AqaYyZyzbDmrpBFyCtQkQBZ6rZVlpTpNlSBtxx5V1I1g7l27brrkKO1AxcyPFuBsURupIR7pKo3AYPKkRfewGB2XBPWRFYnvuTLD4EjPHtz8ZTsHX1gIqxfOkODUCp6uIN6tlm2kF+oGvz4S8sVerBRU1D6du2xS1tUX7ZZSfA+08EGDgw+TPZoWwex1uVkX8ViFVpL93VQ7AGYxoLkVs+ZXv79+VwtaRO6UoXQM4XuWgpQs3idZlsTegioxVopCNDxI6Z2Hix89G2089vQY3Aphz1SlhTvrlwUTadJFl6ohm5aFgXCPDycQdWyb0MCYJIuhgEdTT6Fi+dvVmdeVKAj/nHyb7fXJsygiiBXDmean5CZ4MjGVwPunSuXceOorSdoJn45pvXZfowIxNdmtgz03Fmo=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: AESK3YGct0TPJBJfNiS6NfxUDQnX2/BEOzrE/BrfGwNwmwVEjDyToUvP1rxDzd64UkkjgFpnkcPfVVXPu6NwzWH+FSqZvSYzRHssbZYOiV0cTT3O1W2mVe5u1ZOzFF/92pocMpzzkxpF/ohrV8Ey51Qkdvl9NRhrKCSCBiljDKqspIaPZkqm/92mnsUQR/lD2iU1dHRutDUsw2FZo7wo1aumoLFhvm1MEk6LvWRe5GQoaQSi+dC1734ySC5nD24b4J5bOsLrJzolBbNgGOm+0g7tPKk7i/TWan3e9O0nJ7Rqmbjvrr2xzcPm1IWVHfKyoN9rAVqBh0jyH4OYOL/yoMhQMi7rk3OVKtm7VJD3GYOQgB804c2OtBIEJgJC+e6MMgFJMOFy8Q57ftnUUGjb/t0c0J0sLJou/gvxZMkzox0FCaMxxUHINVV4pM31itg5OxZWFkPazRvEF7lRyzUdDL5HcWUrq3ezc//J1d5Ze5yXRPlfF2GF4VRHas5d7Y4TH1L9JzgwR7luAFubxGMVxGBU1JnlHrMhfq//PLvUHhQATj9y8z2jKf2nqz2qFKTJXEXeNymlauqoTnDzGa2h3KzxBaQJsYtEnKY00n+lbxCgZPHMnVI//IOtjIfZPmMa1OjRZm1Y/93gOBWzAmm55dn/ERaXFIPObpV93ivDVbM=
    on:
      branch: master
      tags: true
      repo: flekschas/camera-2d
